apiVersion: apps/v1
kind: Deployment
metadata:
name: jenkins-pipeline
spec:
containers:
    - name: jenkins-pipeline
      image: ismailsimsekdev/jenkins-pipeline
      imagePullPolicy: Always
      ports:
      - containerPort: 8090
        name: jenkins-pipeline

---
apiVersion: v1
kind: Service
metadata:
name: jenkins-pipeline
labels:
  app: jenkins-pipeline
spec:
ports:
  - port: 8090
    targetPort: 8090
selector:
  app: jenkins-pipeline
  tier: jenkins-pipeline
type: LoadBalancer