apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-pipeline
  labels:
    name: jenkins-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-pipeline
  template:
    metadata:
      labels:
        app: jenkins-pipeline
  spec:
  containers:
  - name: jenkins-pipeline
    image: ismalsimsekdev/jenkins-pipeline
    ports:
      - containerPort: 8090
