apiVersion: apps/v1
kind: Deployment
metadata:
name: maven-dockerfile
labels:
  app: maven-dockerfile
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: maven-dockerfile
      tier: maven-dockerfile
  spec:
    containers:
    - name: jenkins-pipeline
      image: ismailsimsekdev/jenkins-pipeline:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8090
        name: jenkins-pipeline

---
apiVersion: v1
kind: Service
metadata:
name: maven-dockerfile
labels:
  app: maven-dockerfile
spec:
ports:
  - port: 8090
    targetPort: 8090
selector:
  app: maven-dockerfile
  tier: maven-dockerfile
type: LoadBalancer